import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

type Pet={id:string;name:string;species:string;breed:string;weight:string;notes:string};
type Med={id:string;petId:string;name:string;dose:string;frequency:string;times:string[];start:string;end:string;food:string;instructions:string;vet:string};
type Log={id:string;medId:string;petId:string;scheduled:string;given:string};
const key=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID();
function read<T>(k:string,d:T):T{try{return JSON.parse(localStorage.getItem(k)||"") as T}catch{return d}}
function App(){
 const[pets,setPets]=useState<Pet[]>(()=>read("petkit:pets",[])),[meds,setMeds]=useState<Med[]>(()=>read("petkit:meds",[])),[logs,setLogs]=useState<Log[]>(()=>read("petkit:logs",[]));
 const[tab,setTab]=useState("today"),[pet,setPet]=useState("all"),[petForm,setPetForm]=useState(false),[medForm,setMedForm]=useState(false),[edit,setEdit]=useState<Med|null>(null),[medPet,setMedPet]=useState(""),[toast,setToast]=useState("");
 useEffect(()=>localStorage.setItem("petkit:pets",JSON.stringify(pets)),[pets]);useEffect(()=>localStorage.setItem("petkit:meds",JSON.stringify(meds)),[meds]);useEffect(()=>localStorage.setItem("petkit:logs",JSON.stringify(logs)),[logs]);
 const active=meds.filter(m=>m.start<=key()&&(!m.end||m.end>=key())).filter(m=>pet==="all"||m.petId===pet);
 const due=useMemo(()=>active.flatMap(m=>m.times.map(t=>({m,t}))).sort((a,b)=>a.t.localeCompare(b.t)),[active]);
 const given=new Set(logs.filter(l=>l.given.slice(0,10)===key()).map(l=>l.id));
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const give=(m:Med,t:string)=>{const id=m.id+"|"+t;if(given.has(id))return;setLogs(x=>[...x,{id,medId:m.id,petId:m.petId,scheduled:key()+"T"+t,given:new Date().toISOString()}]);flash("Dose recorded.")};
 const removePet=(id:string)=>{if(!confirm("Delete this pet and its medication history?"))return;setPets(x=>x.filter(p=>p.id!==id));setMeds(x=>x.filter(m=>m.petId!==id));setLogs(x=>x.filter(l=>l.petId!==id))};
 const removeMed=(id:string)=>{if(!confirm("Delete this medication and its history?"))return;setMeds(x=>x.filter(m=>m.id!==id));setLogs(x=>x.filter(l=>l.medId!==id))};
 return <div className="app"><header><div><b>PetKit 🐾</b><small>Medication tracking for pets.</small></div><button className="primary" onClick={()=>{if(!pets.length){setTab("pets");setPetForm(true)}else{setMedPet(pet==="all"?pets[0].id:pet);setMedForm(true)}}}>+ Medication</button></header>
 {toast&&<div className="toast">{toast}</div>}
 <main>
 {tab==="today"&&<Today pets={pets} due={due} given={given} pet={pet} setPet={setPet} give={give} addPet={()=>setPetForm(true)}/>}
 {tab==="pets"&&<Pets pets={pets} meds={meds} add={()=>setPetForm(true)} med={id=>{setMedPet(id);setMedForm(true)}} edit={m=>{setEdit(m);setMedPet(m.petId);setMedForm(true)}} removePet={removePet} removeMed={removeMed}/>}
 {tab==="history"&&<History pets={pets} meds={meds} logs={logs}/>}
 {tab==="settings"&&<Settings pets={pets} meds={meds} logs={logs} flash={flash}/>}
 </main><div className="ad"><span>Advertisement</span><div>Reserved ad space</div></div>
 <nav>{[["today","⌂","Today"],["pets","🐾","Pets"],["history","◷","History"],["settings","⚙","Settings"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])} key={x[0]}><i>{x[1]}</i>{x[2]}</button>)}</nav>
 {petForm&&<PetModal close={()=>setPetForm(false)} save={p=>{setPets(x=>[...x,p]);setPetForm(false);flash("Pet added.")}}/>}
 {medForm&&<MedModal pets={pets} petId={medPet} initial={edit} close={()=>{setMedForm(false);setEdit(null)}} save={m=>{setMeds(x=>edit?x.map(a=>a.id===m.id?m:a):[...x,m]);setMedForm(false);setEdit(null);flash(edit?"Medication updated.":"Medication added.")}}/>}
 </div>
}
function Today({pets,due,given,pet,setPet,give,addPet}:any){
 const now=new Date().toTimeString().slice(0,5),nowItems=due.filter((x:any)=>x.t<=now&&!given.has(x.m.id+"|"+x.t)),up=due.filter((x:any)=>x.t>now&&!given.has(x.m.id+"|"+x.t)),done=due.filter((x:any)=>given.has(x.m.id+"|"+x.t));
 return <section><div className="hero"><div><label>TODAY · {new Date().toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</label><h1>Keep every dose<br/>on track.</h1><p>See what your pets need today, then record what you give.</p></div><strong>🐶</strong></div>
 {!pets.length?<Empty title="Add your first pet" text="PetKit keeps your data on this device." action="Add a pet" onClick={addPet}/>:<><div className="filters">{["all",...pets.map((p:Pet)=>p.id)].map((id:any)=><button className={pet===id?"selected":""} onClick={()=>setPet(id)} key={id}>{id==="all"?"All pets":pets.find((p:Pet)=>p.id===id)?.name}</button>)}</div>{nowItems.length>0&&<Group title="NOW"items={nowItems}give={give}/>} {up.length>0&&<Group title="UPCOMING"items={up}give={give}/>} {done.length>0&&<Group title="COMPLETED"items={done}give={give}done/>}{!due.length&&<Empty title="Nothing scheduled today" text="Your dashboard is clear."/>}</>}</section>
}
function Group({title,items,give,done}:any){return <div className="group"><label>{title}</label>{items.map((x:any)=><article className={"dose "+(done?"done":"")} key={x.m.id+x.t}><time>{fmt(x.t)}</time><div><b>{x.m.name}</b><span>{x.m.dose} · {x.m.frequency}</span><small>{x.m.instructions||food(x.m.food)}</small></div><button disabled={done} onClick={()=>give(x.m,x.t)}>{done?"✓":"Mark given"}</button></article>)}</div>}
function Pets({pets,meds,add,med,edit,removePet,removeMed}:any){return <section><div className="head"><div><label>YOUR PETS</label><h1>Pet profiles</h1></div><button className="primary" onClick={add}>+ Pet</button></div>{!pets.length?<Empty title="No pets yet" text="Create a profile before adding medication." action="Add pet" onClick={add}/>:<div className="cards">{pets.map((p:Pet)=><article className="pet"><div className="avatar">{p.species==="Cat"?"🐱":"🐶"}</div><div className="grow"><h2>{p.name}</h2><span>{p.species}{p.breed?" · "+p.breed:""}{p.weight?" · "+p.weight:""}</span>{p.notes&&<p>{p.notes}</p>}<div className="meds"><b>Medications</b>{meds.filter((m:Med)=>m.petId===p.id).map((m:Med)=><div className="mini" key={m.id}><span>{m.name} · {m.dose}</span><span><button onClick={()=>edit(m)}>Edit</button><button className="danger" onClick={()=>removeMed(m.id)}>Delete</button></span></div>)}{!meds.some((m:Med)=>m.petId===p.id)&&<small>No medications added.</small>}</div><div className="actions"><button className="secondary" onClick={()=>med(p.id)}>+ Medication</button><button className="ghost danger" onClick={()=>removePet(p.id)}>Delete pet</button></div></div></article>)}</div>}</section>}
function History({pets,meds,logs}:any){const[p,setP]=useState("all");const rows=logs.filter((l:Log)=>p==="all"||l.petId===p).sort((a:Log,b:Log)=>b.given.localeCompare(a.given));return <section><div className="head"><div><label>RECORDS</label><h1>Medication history</h1></div></div><div className="pad"><select value={p} onChange={e=>setP(e.target.value)}><option value="all">All pets</option>{pets.map((x:Pet)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="history">{rows.length?rows.map((l:Log)=><div className="row" key={l.id}><b>✓</b><div><strong>{meds.find((m:Med)=>m.id===l.medId)?.name||"Medication"}</strong><small>{pets.find((p:Pet)=>p.id===l.petId)?.name} · scheduled {new Date(l.scheduled).toLocaleString()} · given {new Date(l.given).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div></div>):<Empty title="No recorded doses" text="Marked doses will appear here."/>}</div></section>}
function Settings({pets,meds,logs,flash}:any){const[permission,setPermission]=useState(("Notification"in window)?Notification.permission:"unsupported");const notify=async()=>{if(!("Notification"in window)){flash("Notifications are not supported here.");return}const p=await Notification.requestPermission();setPermission(p);flash(p==="granted"?"Notifications enabled.":"Permission not granted.")};const backup=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({pets,meds,logs},null,2)],{type:"application/json"}));a.download="petkit-backup.json";a.click()};return <section><div className="head"><div><label>PREFERENCES</label><h1>Settings</h1></div></div><div className="setting"><div><b>Device notifications</b><p>Permission flow for supported browsers. V1 remains local/offline.</p></div><button className="secondary" onClick={notify}>{permission==="granted"?"Enabled":"Enable"}</button></div><div className="setting"><div><b>Backup your data</b><p>Export pets, medications and dose history as JSON.</p></div><button className="secondary" onClick={backup}>Export</button></div><div className="safety"><b>Safety</b><p>PetKit is a tracker, not a veterinary decision tool. It does not diagnose, prescribe, recommend doses, or alter veterinary instructions.</p></div></section>}
function PetModal({close,save}:any){const[f,setF]=useState({name:"",species:"Dog",breed:"",weight:"",notes:""});return <Modal title="Add pet"close={close}><Field label="Name"v={f.name}set={(v:string)=>setF({...f,name:v})}/><div className="two"><Field label="Species"v={f.species}set={(v:string)=>setF({...f,species:v})} select={["Dog","Cat","Bird","Rabbit","Other"]}/><Field label="Weight"v={f.weight}set={(v:string)=>setF({...f,weight:v})}/></div><Field label="Breed"v={f.breed}set={(v:string)=>setF({...f,breed:v})}/><Field label="Notes"v={f.notes}set={(v:string)=>setF({...f,notes:v})} area/><button className="primary wide" disabled={!f.name.trim()} onClick={()=>save({id:uid(),...f})}>Save pet</button></Modal>}
function MedModal({pets,petId,initial,close,save}:any){const[f,setF]=useState<Med>(initial||{id:uid(),petId,name:"",dose:"",frequency:"Once daily",times:["08:00"],start:key(),end:"",food:"either",instructions:"",vet:""});const set=(k:keyof Med,v:any)=>setF({...f,[k]:v});return <Modal title={initial?"Edit medication":"Add medication"}close={close}><Field label="Pet"v={f.petId}set={(v:string)=>set("petId",v)}select={pets.map((p:Pet)=>p.id)}selectLabels={pets.map((p:Pet)=>p.name)}/><Field label="Medication name"v={f.name}set={(v:string)=>set("name",v)}/><div className="two"><Field label="Dose"v={f.dose}set={(v:string)=>set("dose",v)}/><Field label="Frequency"v={f.frequency}set={(v:string)=>set("frequency",v)}select={["Once daily","Twice daily","Three times daily","Every 4 hours","Every 6 hours","Every 8 hours","As directed"]}/></div><label>Administration times</label>{f.times.map((t,i)=><input className="time" type="time" value={t} key={i} onChange={e=>set("times",f.times.map((x,j)=>j===i?e.target.value:x))}/>)}<button className="link" onClick={()=>set("times",[...f.times,"12:00"])}>+ Add time</button><div className="two"><Field label="Start date"v={f.start}set={(v:string)=>set("start",v)}type="date"/><Field label="End date"v={f.end}set={(v:string)=>set("end",v)}type="date"/></div><Field label="Food instruction"v={f.food}set={(v:string)=>set("food",v)}select={["either","with","without"]}selectLabels={["No preference recorded","With food","Without food"]}/><Field label="Instructions"v={f.instructions}set={(v:string)=>set("instructions",v)} area/><Field label="Vet / clinic (optional)"v={f.vet}set={(v:string)=>set("vet",v)}/><button className="primary wide" disabled={!f.name.trim()||!f.dose.trim()} onClick={()=>save(f)}>{initial?"Save changes":"Add medication"}</button></Modal>}
function Field({label,v,set,select,selectLabels,area,type="text"}:any){return <label>{label}{select?<select value={v} onChange={e=>set(e.target.value)}>{select.map((x:string,i:number)=><option value={x} key={x}>{selectLabels?selectLabels[i]:x}</option>)}</select>:area?<textarea value={v} onChange={e=>set(e.target.value)}/>:<input type={type} value={v} onChange={e=>set(e.target.value)}/>}</label>}
function Modal({title,close,children}:any){return <div className="overlay"><div className="modal"><div className="modalhead"><h2>{title}</h2><button className="close" onClick={close}>×</button></div>{children}</div></div>}
function Empty({title,text,action,onClick}:any){return <div className="empty"><div>🐾</div><h2>{title}</h2><p>{text}</p>{action&&<button className="primary" onClick={onClick}>{action}</button>}</div>}
function fmt(t:string){const[a,b]=t.split(":").map(Number),d=new Date();d.setHours(a,b);return d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
function food(f:string){return f==="with"?"Give with food":f==="without"?"Give without food":"No food instruction"}
createRoot(document.getElementById("root")!).render(<App/>);